# Generated by Django 3.2 on 2021-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevUserBsc',
            fields=[
                ('mem_sno', models.DecimalField(db_column='MEM_SNO', decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('mem_curhold_sum', models.DecimalField(blank=True, db_column='MEM_CURHOLD_SUM', decimal_places=0, max_digits=18, null=True)),
                ('mem_curchrg_sum', models.DecimalField(blank=True, db_column='MEM_CURCHRG_SUM', decimal_places=0, max_digits=18, null=True)),
                ('mem_curaccum_sum', models.DecimalField(blank=True, db_column='MEM_CURACCUM_SUM', decimal_places=0, max_digits=18, null=True)),
                ('mem_cursubs_sum', models.DecimalField(blank=True, db_column='MEM_CURSUBS_SUM', decimal_places=0, max_digits=18, null=True)),
                ('mem_curgift_sum', models.DecimalField(blank=True, db_column='MEM_CURGIFT_SUM', decimal_places=0, max_digits=18, null=True)),
                ('mem_curcashout_sum', models.DecimalField(blank=True, db_column='MEM_CURCASHOUT_SUM', decimal_places=0, max_digits=18, null=True)),
                ('mem_curprch_sum', models.DecimalField(blank=True, db_column='MEM_CURPRCH_SUM', decimal_places=0, max_digits=18, null=True)),
                ('mem_curpay_sum', models.DecimalField(blank=True, db_column='MEM_CURPAY_SUM', decimal_places=0, max_digits=18, null=True)),
                ('mem_curgcard_sum', models.DecimalField(blank=True, db_column='MEM_CURGCARD_SUM', decimal_places=0, max_digits=18, null=True)),
                ('sum_accu_startdttm', models.CharField(blank=True, db_column='SUM_ACCU_STARTDTTM', max_length=14, null=True)),
                ('pay_pwd', models.CharField(blank=True, db_column='PAY_PWD', max_length=100, null=True)),
                ('refund_bank_cd', models.CharField(blank=True, db_column='REFUND_BANK_CD', max_length=5, null=True)),
                ('refund_acc', models.CharField(blank=True, db_column='REFUND_ACC', max_length=50, null=True)),
                ('refund_acc_holder', models.CharField(blank=True, db_column='REFUND_ACC_HOLDER', max_length=100, null=True)),
                ('svc_alarm_rcvyn', models.CharField(db_column='SVC_ALARM_RCVYN', max_length=1)),
                ('event_alarm_rcvyn', models.CharField(db_column='EVENT_ALARM_RCVYN', max_length=1)),
                ('mem_sece_dttm', models.CharField(blank=True, db_column='MEM_SECE_DTTM', max_length=14, null=True)),
                ('mem_cert_nm', models.CharField(blank=True, db_column='MEM_CERT_NM', max_length=100, null=True)),
                ('mem_sex', models.CharField(blank=True, db_column='MEM_SEX', max_length=3, null=True)),
                ('mem_nat', models.CharField(blank=True, db_column='MEM_NAT', max_length=3, null=True)),
                ('self_cert_dt', models.CharField(blank=True, db_column='SELF_CERT_DT', max_length=14, null=True)),
                ('self_cert_ci', models.CharField(blank=True, db_column='SELF_CERT_CI', max_length=100, null=True)),
                ('self_cert_di', models.CharField(blank=True, db_column='SELF_CERT_DI', max_length=100, null=True)),
                ('reg_dttm', models.CharField(blank=True, db_column='REG_DTTM', max_length=14, null=True)),
                ('reger', models.CharField(blank=True, db_column='REGER', max_length=50, null=True)),
                ('mod_dttm', models.CharField(blank=True, db_column='MOD_DTTM', max_length=14, null=True)),
                ('moder', models.CharField(blank=True, db_column='MODER', max_length=50, null=True)),
                ('del_yn', models.CharField(db_column='DEL_YN', max_length=1)),
                ('mem_dv_cd', models.CharField(blank=True, db_column='MEM_DV_CD', max_length=1, null=True)),
            ],
            options={
                'db_table': 'dev_user_bsc',
                'managed': False,
            },
        ),
    ]
