# Generated by Django 3.2 on 2021-05-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devboardbsc',
            options={'managed': False, 'ordering': ('-insert_dt',)},
        ),
    ]
