# Generated by Django 3.2 on 2021-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevBoardBsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('hit', models.DecimalField(decimal_places=0, max_digits=10)),
                ('insert_dt', models.DateTimeField()),
                ('update_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'dev_board_bsc',
                'managed': False,
            },
        ),
    ]
